## Creating numpy arrays / n-d arrays

1. using np.array()
2. using np.zeros() , np.ones(), np.empty(), np.random()
3. using np.arrange() with .reshape()
4. using np.linspace()
5. using copy()
6. using identity()
7. using np.random.randint()

In [1]:
#creating n-d arrays
import numpy as np

In [2]:
# np.array()
# 1-d arrray
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
# 3-d array
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
# intializing with zeros , ones, etc...
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
arr4 = np.ones((3,3,3))
arr4
# by default each element will be float

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
# creating identity matrix
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# using arange
arr6 = np.arange(5,16)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
arr6 = np.arange(1,11,2)
arr6

array([1, 3, 5, 7, 9])

In [20]:
# using linespace,to get values between 2 limits spaced equally
arr7 = np.linspace(1,10,20)
arr7

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
# coorect way to copy
arr8 = arr7.copy()
arr8

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [40]:
# using reshape
arr6 = np.arange(1,21)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
arr6.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [42]:
arr6.reshape(2,11)

ValueError: cannot reshape array of size 20 into shape (2,11)

In [43]:
arr6.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
arr6.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [144]:
arr7 = np.random.randint(low = 1,high = 300,size=20).reshape(5,4)
arr7

array([[ 38, 279, 284,  90],
       [207,  85, 165, 173],
       [296, 126, 208, 227],
       [248, 230, 203, 133],
       [124,  41,  73, 207]])

## Attributes

1. .shape
2. .ndim
3. .size
4. .itemsize
5. .dtype
6. .astype('int or float or string')

In [22]:
# getting shape
arr2.shape

(2, 2, 3)

In [24]:
# getting dimensions
arr2.ndim

3

In [25]:
arr1.ndim

1

In [26]:
arr1.shape

(4,)

In [27]:
# getting size total number of items
arr1.size

4

In [28]:
arr2.size

12

In [29]:
# getting itemsize gives size of type of data here int so 4 as in bytes
arr1.itemsize

4

In [30]:
arr2.itemsize

4

In [31]:
arr3.itemsize # here float is present so 8 bytes

8

In [32]:
# getting type of data
arr2.dtype

dtype('int32')

In [33]:
arr3.dtype

dtype('float64')

In [35]:
# changeing types
arr2.astype('float')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [49]:
arr3.astype('int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [48]:
arr2.astype('str')

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['7', '8', '9'],
        ['10', '11', '12']]], dtype='<U11')

## INDEXING, SLICING, ITERATION

In [72]:
ar1 = np.arange(1,21).reshape(4,5)
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
ar1[0,2] # ar1[row,column] indexing

3

In [74]:
ar1[:,:] # slicing

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
ar1[0:2,]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [76]:
ar1[,1:4]

SyntaxError: invalid syntax (3706860637.py, line 1)

In [77]:
ar1[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [78]:
ar1[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [79]:
ar1[1:-1,1:-1] = np.zeros((2,3))

In [80]:
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16, 17, 18, 19, 20]])

In [83]:
ar2 = np.arange(1,31).reshape(6,5)
ar2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [84]:
# to get lists
for i in ar2:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]


In [85]:
for i in ar2:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [86]:
# it can also be done with iteration
for i in np.nditer(ar2):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


## Operations

In [91]:
ar1 = np.arange(1,17).reshape(4,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
ar2 = np.arange(17,33).reshape(4,4)
ar2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [94]:
ar1 + ar2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [98]:
ar1*ar2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [96]:
ar1-ar2

array([[-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16],
       [-16, -16, -16, -16]])

In [99]:
ar1 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [145]:
arr7[arr7>50] # boolean indexing

array([279, 284,  90, 207,  85, 165, 173, 296, 126, 208, 227, 248, 230,
       203, 133, 124,  73, 207])

In [146]:
arr7[(arr7>100) & (arr7%2 != 0)]

array([279, 207, 165, 173, 227, 203, 133, 207])

In [101]:
ar3 = np.arange(6).reshape(2,3)
ar4 = np.arange(6,12).reshape(3,2)

In [102]:
ar3

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
ar4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [106]:
ar3.dot(ar4) # dot product can be done with (2,3) (3,2)

array([[ 28,  31],
       [100, 112]])

In [107]:
ar3.max()

5

In [108]:
ar4.max()

11

In [109]:
ar4.min()

6

In [110]:
# using axis, axis= 0 means column wise, axis= 1 means row wise
ar4.max(axis=0)

array([10, 11])

In [111]:
ar4.max(axis=1) # as there are 3 rows each has a max of 7,8,11

array([ 7,  9, 11])

In [112]:
ar4.sum()

51

In [113]:
ar4.sum(axis=0)

array([24, 27])

In [114]:
ar4.sum(axis=1)

array([13, 17, 21])

In [116]:
ar4.mean()

8.5

In [117]:
ar4.std() # standard deviation

1.707825127659933

In [118]:
np.sin(ar4) #also can be done cos, tan

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [119]:
np.median(ar4)

8.5

In [120]:
np.exp(ar4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [121]:
np.log(ar4)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [122]:
np.sqrt(ar4)

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

## RESHAPE
1. ravel
2. reshape
3. transpose
4. stacking
5. spitting

In [128]:
ar4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [123]:
ar4.ndim

2

In [124]:
ar4.ravel() # converts n-d array to 1-d array

array([ 6,  7,  8,  9, 10, 11])

In [125]:
ar4.transpose() # row to column , column to row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [126]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [127]:
arr2.transpose()

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [130]:
ar5 = ar4.transpose().copy()
ar5

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [131]:
ar3

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
np.vstack((ar3,ar5,ar3)) #vstack combines vertically increases number of rows takes 1 tuple as input

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  8, 10],
       [ 7,  9, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [138]:
np.hstack((ar3,ar5))# hstack combines horizantaly increses columns takes 1 tuple as input

array([[ 0,  1,  2,  6,  8, 10],
       [ 3,  4,  5,  7,  9, 11]])

In [140]:
np.vsplit(ar5,2)

[array([[ 6,  8, 10]]), array([[ 7,  9, 11]])]

In [141]:
np.hsplit(ar5,3)

[array([[6],
        [7]]),
 array([[8],
        [9]]),
 array([[10],
        [11]])]